title:
description:
logo: # 120x120 px default
teaser: # 400x250 px default
locale:
baseurl: /MediaConch
collections: 
  releasenotes:
    output: true
  documentation:
    output: true

sass:
    sass_dir: _sass
    style: compressed
permalink: :year/:month/:day/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - github-pages

owner:
  name:
  email:
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar:
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json", "HowToBuild.txt"]
